spring:
  config:
    import: optional:file:../.env[.properties]

  application:
    name: Fidely-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/fidely_DB
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql

  flyway:
    enabled: true

fidely:
  api-url:
    url: http://localhost:8080/

  security:
    jwt:
      secret: ${FIDELY_JWT_SECRET}
      access-token-expiration-minutes: 15
      email-verification-token-expiration-minutes: 60